=== pilarrus/gym/xml/dtd/monitores.dtd
<!ELEMENT monitores (monitor+)>
<!ELEMENT monitor (foto, descripcion)>
<!ATTLIST monitor
          apellido CDATA #REQUIRED
          nombre CDATA #REQUIRED>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto
          ruta CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>

=== pilarrus/gym/xml/monitores.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE monitores SYSTEM "dtd/monitores.dtd">
<monitores>

	<monitor nombre="Noa" apellido="Romero">
		<foto ruta="img/monitores/noa.jpeg"/>
		<descripcion>Experta en Zumba y Spinnig</descripcion>
	</monitor>

	<monitor nombre="Pedro" apellido="Abad">
		<foto ruta="img/monitores/pedro.jpeg"/>
		<descripcion>Musculación y experto en Fullbody</descripcion>
	</monitor>

	<monitor nombre="Leticia" apellido="Baldonado">
		<foto ruta="img/monitores/leticia.jpeg"/>
		<descripcion>Cardio</descripcion>
	</monitor>

	<monitor nombre="Marta" apellido="Correa">
		<foto ruta="img/monitores/marta.jpeg"/>
		<descripcion>Socorrista</descripcion>
	</monitor>

	<monitor nombre="Gerard" apellido="Ferrer">
		<foto ruta="img/monitores/gerard.jpeg"/>
		<descripcion>Experto en Krav Maga</descripcion>
	</monitor>

	<monitor nombre="Miguel" apellido="Diaz">
		<foto ruta="img/monitores/miguel.jpeg"/>
		<descripcion>Experto en Kick Boxing y Boxeo</descripcion>
	</monitor>

	<monitor nombre="César" apellido="Torres">
		<foto ruta="img/monitores/cesar.jpeg"/>
		<descripcion>Experto en Pilates y Telas</descripcion>
	</monitor>

</monitores>
